name: Build Extension

on:
  push:
    branches:
      - master  # Adjust branch name if necessary
  pull_request:
    branches:
      - master  # Adjust branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Choose the desired Node.js version

      - name: Install dependencies
        run: npm install  # Or use 'yarn install' if you prefer Yarn

      
